routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('layouts.app');
// });

// Route::get('article/add', 'ManoController@articleAdd')->name('article.add');

Route::resource('articles' , 'ArticleController');
Route::get('/', 'ArticleController@index');

// Route::open(['article' => 'article.arcticlecontroller'])
// Route::post('article', 'arcticlecontroller@article')->name('route.newArticle');
Auth::routes();

Route::get('/home', 'ArticleController@index');

Route::resource('categories', 'CategoryController');

// Route::get('categories/{id}', 'CategoryController@show')->name('category.item');

// user routes
Route::get('profile', 'UserController@profile')->name('profile')->middleware('auth');
Route::put('profile', 'UserController@update')->name('profile.update')->middleware('auth');

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $fillable = [
    'title',
    'img_url',
    'mini_description',
    'description',
    'category_id',
    ];
     public function category()
     {
         return $this->belongsTo('App\Category');
     }
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\Category;
use Illuminate\Http\Request;

class ArticleController extends Controller
{
    public function __construct(){
      $this->middleware('auth.Admin')->except(['index','show']);

      $this->middleware('auth')->except(['index']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //  $articles = Article::orderBy('id', 'desc')->paginate(9);
        //  return view('article.index' , compact('articles'));

         $search = \Request::get('search');
         $articles = Article::where('title', 'like', '%'.$search.'%')->orderBy('id','desc')->paginate(9);
         return view('article.index' , compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        return view('article.form', compact('categories'));

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // $article   = new Article ;
        // $article ->title = $request->title;
        // $Article ->image = $request->image;
        // $Article ->article = $request->article;
        // $article->author = 'Saulius';
        // $article->image = 'dasdasdas';
        // $article->article = 'dasdasdas';
        // $article ->save();
        // return $article->all();

        $this->validate($request, [

          'title' => 'required|max:255',
          'img_url' => 'required|image',
          'mini_description' => 'required|string|max:255',
          'description' => 'required|string',
          'category_id' => 'required|exists:categories,id',
       ]);

        if ($request->hasFile('img_url')) {
            $file = $request->file('img_url');
            $file->store('public'); // Panaudoti php artisan storage:link kad susieti public ir storage folderius.
            $request->img_url = $file->hashName();
        }

        Article::create([
          'title' => $request->get('title'),
        //   'img_url' => $request->get('img_url'),
          'img_url' => $request->img_url,
          'mini_description' => $request->get('mini_description'),
          'description' => $request->get('description'),
          'category_id' => $request->get('category_id'),
        ]);

        return redirect()->route('articles.index')->with('message', [
        'text' => 'Naujiena sukurta ivykdytas',
        'type' => 'success'
        ]);
      }

    /**
     * Display the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //  return view('article.show');
        $article = Article::find($id);
        return view('article.show', compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::find($id);
        $categories = Category::all();
        return view('article.form', compact('article', 'categories' ));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Article $article)
    {
        // Article::find($article)->update($request->all());

        $this->validate($request, [

          'title' => 'required|max:255',
          'img_url' => 'image',
          'mini_description' => 'required|string|max:255',
          'description' => 'required|string',
       ]);

        $article->title =  $request->get('title');
        $article->mini_description = $request->get('mini_description');
        // $article->category_id = $request->get('category_id');
        // $article->max = $request->get('description');

        if($request->get('description')){
          $article->description = $request->get('description');
        }
        if($request->get('category_id')){
          $article->description = $request->get('category_id');
        }

        if ($request->hasFile('img_url')) {
            $file = $request->file('img_url');
            $file->store('public');
            $article->img_url = $file->hashName();
          }

          $article->save();
          return redirect()->route('articles.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Article  $article
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $article->delete();

        return redirect()->route('articles.index');
    }
}

resources/views/article/form.blade.php
@extends('layouts.app')

@section('content')


    <div class="row">
    	<div class="col-md-6  col-md-offset-3">

        @if(isset($article))
            {{-- Editinimo forma --}}
          {!! Form::model($article, ['route' => ['articles.update', $article->id], 'method' => 'put', 'files' => true])  !!}
        @else
            {{-- Naujai sukurti forma --}}
          {!! Form::open(['route' => ['articles.store'], 'method' => 'post', 'files' => true])  !!}
        @endif

{{-- <div class="form-group">
    {!! Form::label('category_id', 'Categorija');!!}
	{!! Form::select('category_id', $article, null, ['class' =>'form-control']) !!}
</div> --}}





    			<div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
    				{!! Form::label('title', 'Title');!!}
            {!! Form::text('title', null, ['class' => 'form-control', 'placeholder' => 'Enter title']);!!}

            @if ($errors->has('title'))
              <span class="help-block">
                  <strong>{{ $errors->first('title') }}</strong>
              </span>
            @endif

    			</div>

          <div class="form-group{{ $errors->has('mini_description') ? ' has-error' : '' }}">
    				{!! Form::label('mini_description', 'Mini description');!!}
            {!! Form::text('mini_description', null, ['class' => 'form-control', 'placeholder' => 'Enter title']);!!}

            @if ($errors->has('mini_description'))
              <span class="help-block">
                  <strong>{{ $errors->first('mini_description') }}</strong>
              </span>
            @endif

    			</div>

    			<div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
            {!! Form::label('description', 'Description');!!}
    				{!! Form::textarea('description', null, ['class' => 'form-control', 'placeholder' => 'Enter description']);!!}

            @if ($errors->has('description'))
              <span class="help-block">
                  <strong>{{ $errors->first('description') }}</strong>
              </span>
            @endif

    			</div>

    			<div class="form-group{{ $errors->has('category_id') ? ' has-error' : '' }}">
              {!! Form::label('category_id', 'Category: ');!!}

              <select class="selectpicker form-control" name="category_id" title="Pasirink ketegorija">
                  @foreach ($categories as $category)
                      <option value="{{ $category->id }}">{{$category->name}}</option>
                  @endforeach
              </select>

              @if ($errors->has('category_id'))
                <span class="help-block">
                    <strong>{{ $errors->first('category_id') }}</strong>
                </span>
              @endif

    			</div>

                {{-- <div class="form-group">
    			    {!! Form::label('img_url', 'Image');!!}
                    {!! Form::text('img_url', null, ['class' => 'form-control', 'placeholder' => 'Image url']);!!}
    			</div> --}}

    			<div class="form-group{{ $errors->has('img_url') ? ' has-error' : '' }}">
            {!! Form::label('img_url', 'Upload image');!!}
            {!! Form::file('img_url');!!}

            @if ($errors->has('img_url'))
              <span class="help-block">
                  <strong>{{ $errors->first('img_url') }}</strong>
              </span>
            @endif

    			</div>

        {!! Form::submit('Submit', ['class' => 'btn btn-primary','onclick'=>"this.disabled=true;this.form.submit();" ]); !!}
    		{!! Form::close() !!}
    	</div>
    </div>


@endsection

resources/views/article/index.blade.php
@extends('layouts.app')

@section('content')

  @foreach ($articles->chunk(3) as $chunk)
    <div class="row">
      @foreach ($chunk as $article)
          <div class="col-md-4 newimg">
              <a href="{{ route('articles.show', $article->id) }}">

                  
                    <img class="img-responsive text-center" src="{{ asset('/storage/' . $article->img_url) }}" alt="{{ $article->title }}">

                  <h3>{{ $article->title }}</h3>
              </a>
              <p>{{ $article->mini_description }}</p>
          </div>
        @endforeach
      </div>
    @endforeach
<div class="text-center">
    {!! $articles->links(); !!}
</div>
@endsection

resources/views/article/show.blade.php
@extends('layouts.app')

@section('content')


    <div class="row">
        <div class="col-md-12 naujiena">
            <h1 class="text-center">{{ $article->title}}</h1>
            <img class="img-responsive text-center" src="{{ asset('/storage/' . $article->img_url) }}" alt="{{ $article->title }}">
            <div class="naujiena">
                <p>{!! $article->description !!}</p>
                <hr/>
                <p>Kategorija: {{ $article->category->name }}</p>
             </div>

          </div>
     </div>
@if(Auth::user() && Auth::user()->isAdmin())
       <a href="{{ route('articles.edit', $article->id) }}" class="btn btn-primary">Edit</a>
     {!! Form::open(['route' => ['articles.destroy', $article->id], 'method' => 'delete', 'class' => 'pull-right','onclick'=>"return myFunction()"])  !!}
     {!! Form::submit('Delete', ['class'=>'btn btn-danger']) !!}
     {!! Form::close() !!}

@endif
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
/*
var disqus_config = function () {
this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
*/
  (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
      s.src = 'https://info-4.disqus.com/embed.js';
      s.setAttribute('data-timestamp', +new Date());
      (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>





@endsection