routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('layouts.app');
// });

// Route::get('article/add', 'ManoController@articleAdd')->name('article.add');

Route::resource('articles' , 'ArticleController');
Route::get('/', 'ArticleController@index');

// Route::open(['article' => 'article.arcticlecontroller'])
// Route::post('article', 'arcticlecontroller@article')->name('route.newArticle');
Auth::routes();

Route::get('/home', 'ArticleController@index');

Route::resource('categories', 'CategoryController');

// Route::get('categories/{id}', 'CategoryController@show')->name('category.item');

// user routes
Route::get('profile', 'UserController@profile')->name('profile')->middleware('auth');
Route::put('profile', 'UserController@update')->name('profile.update')->middleware('auth');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'categories';

    protected $fillable = [
    'name',
    ];

    public function articles()
    {
        return $this->hasMany('App\Article');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Article;

use Illuminate\Http\Request;
use Session;
class CategoryController extends Controller
{

    public function __construct(){
        $this->middleware('auth.Admin')->except(['index', 'show']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $categories = Category::all();
        // pvz vietoj meniu controoler function daryk
        return view('category.index',[
            'categories' => $categories,
        ]);
        // return view('layouts.app', [ 'article' => $article,'categories' => $categories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(
            'name' => 'required|max:255'
        ));
        // Category::create([
        //   'category' => $request->get('category'),
        // ]);

        $category = new Category;
        $category->name = $request->name;
        $category->save();

        Session::flash('success', 'New Category has been created');
        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
      $articles = Article::orderBy('id', 'desc')->get();
      return view('category.show', compact('category','articles'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        return view('category.form', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Category $category)
    {    $this->validate($request, array(
              'name' => 'required|max:255'
        ));
        Category::find($category)->update($request->all());
        return redirect()->route('categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();

        return redirect()->route('categories.index');
    }
}

resources/views/category/form.blade.php
@extends('layouts.app')

@section('content')

    @if(isset($category))
        {{-- Editinimo forma --}}
      {!! Form::model($category, ['route' => ['categories.update', $category->id], 'method' => 'put'])  !!}
    @else
        {{-- Naujai sukurti forma --}}
      {!! Form::open(['route' => ['categories.store'], 'method' => 'post'])  !!}
    @endif

    <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
        {!! Form::label('name', 'Sukurti kategorija');!!}
        {!! Form::text('name', null, ['class' => 'form-control', 'placeholder' => 'Enter category']);!!}
       @if ($errors->has('name'))
         <span class="help-block">
             <strong>{{ $errors->first('name') }}</strong>
         </span>
       @endif
    </div>
    {!! Form::submit('Submit', ['class' => 'btn btn-primary', 'onclick'=>"this.disabled=true;this.form.submit();"]); !!}
{!! Form::close() !!}

@endsection

resources/views/category/index.blade.php
@extends('layouts.app')

@section('content')

    <div class="row">
        <div class="col-md-12">
            <h1>Kategorijos</h1>
            <table class="table">
                <thead>
                    <tr>
                        <th>Name</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($categories as $category)
                        <tr>
                            <td><a href="{{route('categories.show', $category->id)}}">{{$category->name}}</a>
                              @if(Auth::user() && Auth::user()->isAdmin())
                                <a class="btn btn-primary pull-right" href="{{ route('categories.edit', $category->id)}}"/> Edit </a>
                                {!! Form::open(['route' => ['categories.destroy', $category->id], 'method' => 'delete', 'class' => ' pull-right', 'onclick'=>"return myFunction()"])  !!}
                                {!! Form::submit('Delete', ['class'=>'btn btn-danger']) !!}
                                {!! Form::close() !!}
                                @endif
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

@endsection

resources/views/category/show.blade.php
@extends('layouts.app')

@section('content')



<h2>Kategorijoje
  <b>{{$category->name}}</b>
  <small>yra <strong style="color: red;">{{$category->articles->count()}} naujienos</strong></small>
</h2>




    @foreach ($category->articles->chunk(3) as $chunk)
      <div class="row">
        @foreach ($chunk as $article)
            <div class="col-md-4 newimg">
                <a href="{{ route('articles.show', $article->id) }}">

                      <img class="img-responsive text-center" src="{{ asset('/storage/' . $article->img_url) }}" alt="{{ $article->title }}">

                    <h3>{{ $article->title }}</h3>
                </a>
                <p>{{ $article->mini_description }}</p>
            </div>
          @endforeach
        </div>
      @endforeach
      {{-- <div class="text-center">
          {!! $category->links(); !!}
      </div> --}}
















@endsection